### ISSUE TITLE
Play State/Schematic

### ISSUE THREAD

**Issue by interstaller555** [albnys/Drum-Machine#1]
Amazing Work! Thank you! quick note:
Start/Stop (Pin 37) not annotated in schematic (I asssume it should be momentary to vcc (3.3v?)

**Comment by albnys** [comment]
Yes!
That's right, my bad! Thanks for pointing that out.

**Comment by interstaller555** [comment]
awesome! Thanks! I was able to get this laid out on a 3x5" pcb. happy to share updated diagram as well as gerber files if interested.

**Comment by interstaller555** [comment]
I am curious about adding midi in and/or clocking signals.

**Comment by albnys** [comment]
It´s great that you've made a pcb. would you like to send the files? :)

**Comment by interstaller555** [comment]
Yeah man, I was just going to upload to my git.

**Comment by interstaller555** [comment]
issue resolved
